### ISSUE TITLE
Basic Pitch plugin but label says "Whisper"

### ISSUE THREAD

**Issue by olilarkin** [Ircam-Partiels/basic-pitch-vamp-plugin#29]
Hey Pierre, 

Partiels is great!

I spotted that basic pitch is labelled incorrectly.

There are also a couple of other occurrences...

https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/blob/25534d81c7e583dac5f822045ed212233624708b/source/bpvp.cpp#L198

**Comment by pierreguillot** [comment]
Hi, thank you for your feedback! This should be corrected (#30). However, I couldn't find any other occurrences outside the plugin description (which appeared in the test document).
